name: auto-run-test
on:
  pull_request:
        branches:
          - 'develop'
jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [14, 16]
    if: ${{startsWith(github.head_ref, 'feature/')}}
    steps:
      - uses: actions/checkout@v3
      - name: Use NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v3 
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install build test
      - run: npm install
      - run: npm run
      - run: npm test --coverage > coverage.txt
      - name: create code coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: code coverage
          path: coverage.txt